---
metadata:
  name: .NET Thailand
  short_name: .NET Thailand
  description: .NET Thailand community
  language: en
  pathPrefix: "/"
  siteImage:
  favicon: "/assets/favicon.png"
  themeColor: "#ff0000"
header:
  enabled: true
  logo: "/assets/code.svg"
  logoLink: "/"
  helpUrl: ""
  links:
    - text: .NET Thailand community
      link: https://www.facebook.com/groups/dotnetthailand
      external: true
    - text: Gatsby
      link: https://www.gatsbyjs.org
      external: true
    - text: Docs
      link: "/"
      external: false
sidebar:
  enabled: true
  # forcedNavOrder:
  #   - "/introduction"
  #   - "/configuration/basic"
  #   - "/configuration/advanced"
  # expanded:
  groups:
    - order: 1
      path: "/gettingstarted"
      title: ":rocket: Getting Started"
    - order: 2
      path: "/configuration"
      title: ":wrench: Configuration"
    - order: 3
      path: "/editing"
      title: ":writing_hand: Editing Content"
    - order: 4
      path: "/deployment"
      title: ":rocket: Deployment"
    - order: 5
      path: "/developing"
      title: ":computer: Developing"
  links:
    - text: React
      link: https://reactjs.org
  ignoreIndex: false
  poweredBy:
    trademark: "/assets/gatsby.png"
    name: GatsbyJS
    link: https://www.gatsbyjs.org
pwa:
  enabled: true
  manifest:
    display: standalone
    crossOrigin: anonymous
    icon: "/assets/favicon.png"

social:
  github: https://www.github.com/dotnetthailand
  facebook: https://www.facebook.com/groups/dotnetthailand

features:
  darkMode:
    enabled: true
    default: true
  editOnRepo:
    location: https://github.com/dotnetthailand/dotnetthailand.github.io
    type: github
    editable: true
  mermaid:
    language: "mermaid"
    theme: "dark"
    options:
    width: 400
    height: 300
  pageProgress:
    enabled: true
    includePaths:
      - "/configuration/settingup/features"
    excludePaths:
      - "/"
    height: 3
    prependToBody: false
    color: "#A05EB5"
  previousNext:
    enabled: true
    arrowKeyNavigation: true
  propagateNetlifyEnv: true
  rss:
    enabled: true
    title: BooGi Docs
    showIcon: false
    copyright: "2020, Mateusz Filipowicz"
    webMaster: "Mateusz Filipowicz"
    managingEditor: "Mateusz Filipowicz"
    categories:
      - Docs as Code
      - GatsbyJS
    ttl: 60
    matchRegex: "^/"
    outputPath: "/rss.xml"
    generator: "boogi"
  scrollTop: true
  search:
    enabled: false # Temporary disable search engine
    engine: 'algolia'
    placeholder: 'Search'
    startComponent: 'input' # icon
    excerptSize: 8000
    debounceTime: 380
    snippetLength: 23
    hitsPerPage: 10
    showStats: true
    pagination:
      enabled: true
      totalPages: 10
      showPrevious: true
      showNext: true
  showMetadata: true
  toc:
    show: true
    depth: 4
  fullScreenMode:
    enabled: true
    hideHeader: true
    hideToc: true
    hideSidebar: true
